# Generated by Django 5.1.3 on 2024-12-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningdevelopment',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='educationalbackground',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='voluntarywork',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='civilserviceeligibility',
            name='form_id',
        ),
        migrations.RemoveField(
            model_name='familybackground',
            name='form_id',
        ),
        migrations.DeleteModel(
            name='FormID',
        ),
    ]
