# Generated by Django 5.1.3 on 2024-12-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0002_remove_learningdevelopment_form_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.civilserviceeligibility')),
                ('educational_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.educationalbackground')),
                ('family_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.familybackground')),
                ('learning_development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.learningdevelopment')),
                ('personal_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.personalinformation')),
                ('voluntary_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.voluntarywork')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pds_app.workexperience')),
            ],
        ),
    ]
