# Generated by Django 5.1.3 on 2024-12-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0003_completeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
