# Generated by Django 5.1.3 on 2024-12-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0004_alter_personalinformation_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
