# Generated by Django 5.1.3 on 2024-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0005_alter_personalinformation_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeform',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
