# Generated by Django 5.1.3 on 2024-12-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0007_civilserviceeligibility_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeform',
            name='civil_service',
        ),
        migrations.RemoveField(
            model_name='completeform',
            name='educational_background',
        ),
        migrations.RemoveField(
            model_name='completeform',
            name='learning_development',
        ),
        migrations.RemoveField(
            model_name='completeform',
            name='voluntary_work',
        ),
        migrations.RemoveField(
            model_name='completeform',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='completeform',
            name='civil_service',
            field=models.ManyToManyField(to='pds_app.civilserviceeligibility'),
        ),
        migrations.AddField(
            model_name='completeform',
            name='educational_background',
            field=models.ManyToManyField(to='pds_app.educationalbackground'),
        ),
        migrations.AddField(
            model_name='completeform',
            name='learning_development',
            field=models.ManyToManyField(to='pds_app.learningdevelopment'),
        ),
        migrations.AddField(
            model_name='completeform',
            name='voluntary_work',
            field=models.ManyToManyField(to='pds_app.voluntarywork'),
        ),
        migrations.AddField(
            model_name='completeform',
            name='work_experience',
            field=models.ManyToManyField(to='pds_app.workexperience'),
        ),
    ]
