# Generated by Django 5.1.3 on 2024-12-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0008_remove_completeform_civil_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_third_degree', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Within Third Degree (Y/N)')),
                ('with_fourth_degree', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Within Fourth Degree (Y/N)')),
                ('fourth_degree_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details for Fourth Degree (if any)')),
                ('offense', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Administrative Offense (Y/N)')),
                ('offense_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Administrative Offense')),
                ('criminal', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Criminally Charged (Y/N)')),
                ('criminal_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Criminal Charge')),
                ('criminal_date', models.DateField(blank=True, null=True, verbose_name='Date of Criminal Charge')),
                ('convicted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Convicted of Crime (Y/N)')),
                ('convicted_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Conviction')),
                ('sep_service', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Separated from Service (Y/N)')),
                ('sep_service_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Service Separation')),
                ('candidate', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Candidate in Election (Y/N)')),
                ('candidate_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Election Candidacy')),
                ('resign_candid', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Resigned for Election Campaign (Y/N)')),
                ('resign_candid_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Election Campaign Resignation')),
                ('immigrant_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Immigrant/Permanent Resident Status (Y/N)')),
                ('immigrant_details', models.TextField(blank=True, max_length=200, null=True, verbose_name='Details of Immigration Status')),
                ('indigenous_group_member', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Member of Indigenous Group (Y/N)')),
                ('disability_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Person with Disability (Y/N)')),
                ('solo_parent_status', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=3, verbose_name='Solo Parent (Y/N)')),
                ('reference_name', models.TextField(max_length=200, verbose_name='Reference Name')),
                ('reference_address', models.TextField(max_length=200, verbose_name='Reference Address')),
                ('reference_contact', models.TextField(max_length=200, verbose_name='Reference Contact')),
                ('government_id', models.CharField(max_length=50, verbose_name='Government Issued ID')),
                ('government_id_number', models.CharField(max_length=100, verbose_name='ID/License/Passport Number')),
                ('id_issue_date', models.DateField(blank=True, null=True, verbose_name='ID Issue Date')),
                ('id_issue_place', models.CharField(max_length=100, verbose_name='ID Issue Place')),
                ('date_accomplished', models.DateField(auto_now_add=True, verbose_name='Date Accomplished')),
            ],
        ),
    ]
