# Generated by Django 5.1.3 on 2024-12-04 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0009_otherinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeform',
            name='educational_background',
        ),
        migrations.AddField(
            model_name='completeform',
            name='educational_background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pds_app.educationalbackground'),
            preserve_default=False,
        ),
    ]
