# Generated by Django 5.1.3 on 2024-12-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0010_remove_completeform_educational_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationalbackground',
            name='name',
        ),
    ]
