# Generated by Django 5.1.3 on 2024-12-04 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0011_remove_educationalbackground_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='completeform',
            name='other_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pds_app.otherinformation'),
            preserve_default=False,
        ),
    ]
